In [1]:
import numpy as np

# Existing data

We randomly generated data with shapes (100, 3).
Assume these are 100 samples from 3 groups.
Each sample has a value (float) stored in "data.npy" and a name (string) stored in "names.npy".

In one group, there were fewer samples, and the matrices have been filled with NaNs (data) and empty strings (names).

The NaNs and respective names (see above) are to be ignored in all tasks.
For example, you can use "np.nanmean" instead of "np.mean" to automatically ignore NaNs

In [2]:
%run create_dataset.py

In [3]:
# Load data
dat = np.load('data.npy')
nam = np.load('names.npy')

print the shapes and data types of both arrays

In [5]:
# Enter code:
dat.shape

(100, 3)

In [6]:
nam.shape

(100, 3)

compute the means of all 3 groups, ignore NaNs

In [20]:
# Enter code:
np.nanmean(dat[:, 0])

3.4749240090253686

In [21]:
np.nanmean(dat[:, 1])

3.2619747841691717

In [22]:
np.nanmean(dat[:, 2])

5.00776356055341

compute the means of all 3 groups, but ignore the first 10 and last 10 samples of each group

In [28]:
# Enter code:
np.nanmean(dat[10:90, 0])

3.4430143648331906

In [29]:
np.nanmean(dat[10:90, 1])

3.373043907651342

In [30]:
np.nanmean(dat[10:90, 2])

5.133763123226796

compute the standard deviations and standard errors of all 3 groups

In [36]:
# Enter code:

np.nanstd(dat[:, 0])

1.0090151675389927

In [35]:
np.nanstd(dat[:, 1])

1.1368036109073036

In [37]:
np.nanstd(dat[:, 2])

3.3808420138725315

find the maximum for each group, and the maximum value across all groups

In [38]:
# Enter code:

np.nanmax(dat[:, 0])

6.059347551698167

In [39]:
np.nanmax(dat[:, 1])

5.015752812467621

In [40]:
np.nanmax(dat[:, 2])

16.558194471964164

In [41]:
np.nanmax(dat)

16.558194471964164

create a new array with the same shape and sorted values of each group in descending order (NaNs, come last).

optional: sort the names of each group respectively. hint: use "np.argsort" and "np.take_along_axis"

In [53]:
# Enter code:

dat[:, 1] = np.sort(dat[:, 1])
dat[:, 1]

array([1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.86606598,
       1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.86606598,
       1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.86606598,
       1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.89709293,
       1.90853375, 1.97016885, 2.01757848, 2.06003548, 2.10433424,
       2.16468509, 2.19506638, 2.22642032, 2.27497165, 2.37466341,
       2.40078848, 2.42549214, 2.43928354, 2.48916007, 2.52501448,
       2.52569947, 2.54331559, 2.58071515, 2.63983239, 2.68504158,
       2.74680128, 2.75127173, 2.77398026, 2.78437668, 2.86126542,
       2.98403869, 3.00661057, 3.06460022, 3.10881079, 3.11303983,
       3.12999666, 3.18987764, 3.24342767, 3.26477473, 3.30188438,
       3.36114833, 3.36532604, 3.36786939, 3.55353223, 3.57644188,
       3.58276847, 3.58784188, 3.61831202, 3.65554448, 3.6595883 ,
       3.88872343, 3.93824744, 3.9513447 , 3.99723068, 4.02065558,
       4.04369948, 4.21621088, 4.2165798 , 4.27975194, 4.29030

find the name of the sample with the largest value

In [ ]:
# Enter code:



for the first group, find all values smaller than 3

In [56]:
# Enter code:

dat[:, 1][dat[:, 1] < 3]

#np.where provides indices

array([1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.86606598,
       1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.86606598,
       1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.86606598,
       1.86606598, 1.86606598, 1.86606598, 1.86606598, 1.89709293,
       1.90853375, 1.97016885, 2.01757848, 2.06003548, 2.10433424,
       2.16468509, 2.19506638, 2.22642032, 2.27497165, 2.37466341,
       2.40078848, 2.42549214, 2.43928354, 2.48916007, 2.52501448,
       2.52569947, 2.54331559, 2.58071515, 2.63983239, 2.68504158,
       2.74680128, 2.75127173, 2.77398026, 2.78437668, 2.86126542,
       2.98403869])

for all groups, find all names that start with an a. put them all in a single array

In [62]:
# Enter code:

nam[np.char.startswith(nam, "a")]

array(['atgdfyaewa', 'abaaimamtz', 'aglquzxted', 'aczhdpwjln',
       'aiypmiumik', 'awreoqclba', 'awrmbiubyi', 'akctwzdrwf',
       'ajrzhukwbh', 'amsxcxqetu'], dtype='<U10')

create a new array where the dimensions are swapped. print the shape.

In [65]:
# Enter code:

nam.T.shape

(3, 100)

create a new array from data where every 2nd sample per group is removed. print the shape.

In [1]:
# Enter code:


find the value of the sample with most a's in the name. find all if multiple exist

In [ ]:
# Enter code:

implement three ways to index the 90th sample of the second group.

confirm that all methods give the same value.

hint: the first value of a 1d array in indexed by "arr[0]" and not "arr[1]"

In [4]:
# Enter code:

# New data

create an array with all even numbers between 0 and 100, sorted from highest to lowest

In [97]:
# Enter code:

arr = np.arange(0,101)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [98]:
arr[::-1]

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1,   0])

draw 100 samples from a normal distribution with mean=0 and stddev=3, then drop all values larger than 3 or smaller than -3

In [72]:
# Enter code:

mu, sigma = 0, 3
norm = np.random.normal(mu, sigma, 100)
norm

array([-1.94817508,  2.31628437,  3.33473597,  5.804118  ,  0.20924055,
       -1.91929358, -3.00741579, -3.30537959,  3.7493421 , -4.54528603,
        3.65324546, -2.60532309, -2.05561859, -0.45466637, -2.11096365,
        2.79593926,  5.44003186, -1.97229647, -1.29671352, -0.48996242,
        1.62317029, -0.46045284,  4.16177223,  3.43987175, -3.55638706,
        1.5629045 ,  4.56101771, -1.48434284, -0.88279462, -1.58411099,
       -1.52122685, -5.00535466, -3.98494485,  0.23242116,  4.54079392,
       -1.84008244, -1.92827191,  5.10456321, -3.32477239, -4.98372949,
       -2.48554631, -1.98835344, -5.24235925, -0.38412512,  2.84533905,
       -3.85786432,  0.26273466,  1.18780703, -0.25015283,  0.55707777,
        0.59198179, -2.43818387,  4.49574772,  3.7432705 ,  3.56973419,
        3.04102722, -4.72493841,  2.77818713,  1.96680428, -4.60957084,
       -0.64473107,  0.83038035,  4.99295129,  2.17417157, -2.59369718,
        5.08616538,  0.13133929, -0.76752341, -0.98135459, -4.87

In [87]:
norm = norm[(3 < norm) & (norm > -3)]
norm

array([3.33473597, 5.804118  , 3.7493421 , 3.65324546, 5.44003186,
       4.16177223, 3.43987175, 4.56101771, 4.54079392, 5.10456321,
       4.49574772, 3.7432705 , 3.56973419, 3.04102722, 4.99295129,
       5.08616538, 5.03238879, 4.70471928, 3.87110437, 5.11504244,
       4.84493046])

draw samples from a bionomial distribution with n=10, p=0.5 and shape (20, 3, 4)

In [99]:
# Enter code:

n, p = 10, 0.5

np.random.binomial(n, p, (20, 3,4))

array([[[5, 6, 6, 5],
        [3, 4, 7, 5],
        [5, 4, 4, 7]],

       [[6, 6, 5, 6],
        [4, 6, 5, 5],
        [6, 7, 3, 6]],

       [[4, 5, 2, 4],
        [5, 3, 5, 7],
        [3, 6, 5, 6]],

       [[4, 3, 3, 3],
        [4, 6, 7, 6],
        [6, 3, 4, 4]],

       [[4, 5, 5, 4],
        [4, 7, 6, 4],
        [7, 8, 4, 4]],

       [[5, 7, 7, 3],
        [5, 5, 5, 4],
        [7, 6, 7, 7]],

       [[6, 5, 5, 3],
        [6, 4, 6, 4],
        [3, 3, 1, 6]],

       [[6, 5, 3, 3],
        [2, 3, 7, 4],
        [4, 3, 4, 5]],

       [[5, 4, 3, 5],
        [4, 4, 8, 5],
        [5, 5, 5, 5]],

       [[6, 6, 3, 5],
        [5, 7, 6, 5],
        [3, 5, 3, 4]],

       [[3, 6, 4, 5],
        [7, 4, 5, 5],
        [2, 6, 3, 5]],

       [[5, 6, 6, 4],
        [1, 6, 5, 7],
        [6, 7, 5, 4]],

       [[6, 5, 4, 7],
        [7, 5, 3, 5],
        [6, 7, 4, 3]],

       [[7, 5, 5, 8],
        [3, 6, 3, 4],
        [6, 5, 9, 5]],

       [[4, 4, 4, 4],
        [3, 4, 5, 6],
    

# More complex data

This dataset contains sample from three different plants.
Each sample has 4 attributes (floats), stored in X, and a class / plant index, stored in y.

The attributes in X are:
- sepal length in cm
- sepal width in cm
- petal length in cm
- petal width in cm

The classes in y refer to:
0: Iris-Setosa
1: Iris-Versicolour
2: Iris-Virginica

In [88]:
from sklearn.datasets import load_iris

X, y = load_iris(as_frame=False, return_X_y=True)

Describe the data.

Start with counting the number of samples per class (plant index).

In [113]:
# Enter code:

Summarize the attribute distributions of all 3 classes, e.g. compute means etc.

In [104]:
# Enter code:
np.mean(X[:, 0])

5.843333333333334

In [105]:
np.mean(X[:, 1])

3.0573333333333337

In [106]:
np.mean(X[:, 2])

3.7580000000000005

In [107]:
np.mean(X[:, 3])

1.1993333333333336

# Advanced

Define a function that generates an array of unsigned integers between 0 and 10 of size=(50, 100), i.e. 50 rows and 100 columns

In [7]:
# Enter code:
def sample_test_arr():
    test_arr = np.arange(None # TODO: implement
    return test_arr

In [116]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Implement the following function that finds all rows in this array containing any number at least x times, where x is an integer parameter.
The array itself should also be a parameter.
The return value is an again a 2d array with same dtype, same number of rows, but with potentially fewer columns.

Test the function on the test_arr defined above.

For example, if x=3:
- [0, 1, 1, 2, 1, 3, 4] would be included.
- [0, 1, 2, 2, 1, 3, 1] would be included.
- [0, 1, 2, 2, 1, 3, 3] would not be included.

Make sure no error is raised and the returned shape and data-type is always correct.

In [8]:
def find_all_rows_with_n_reps(arr, x):
    # TODO: Implement
    rows = None
    return rows

test_arr = sample_test_arr()
print(find_all_rows_with_n_reps(arr=test_arr, x=5).shape)
print(find_all_rows_with_n_reps(arr=test_arr, x=15).shape)
print(find_all_rows_with_n_reps(arr=test_arr, x=30).shape)

AttributeError: 'NoneType' object has no attribute 'shape'

Additional task:

- Write a doc-string for the function find_all_rows_with_n_reps.

'Reimplement the function again, but now the repetitions must happen consecutively in each row.

For example, if x=3:
- [0, 1, 1, 2, 1, 3, 4] would be included.
- [0, 1, 2, 2, 1, 3, 1] would not be included.
- [0, 1, 2, 2, 1, 3, 3] would not be included.

Test the function on the test_arr defined above.

In [17]:
def find_all_rows_with_n_consecutive_reps(arr, x):
    # TODO: Implement
    rows = None
    return rows

test_arr = sample_test_arr()
print(find_all_rows_with_n_consecutive_reps(arr=test_arr, x=1).shape)
print(find_all_rows_with_n_consecutive_reps(arr=test_arr, x=2).shape)
print(find_all_rows_with_n_consecutive_reps(arr=test_arr, x=4).shape)
print(find_all_rows_with_n_consecutive_reps(arr=test_arr, x=10).shape)

AttributeError: 'NoneType' object has no attribute 'shape'

For x in {2, 4, 20}, compute the mean number of rows returned for both "find_all_rows_with_n_reps" and "find_all_rows_with_n_consecutive_reps".
Draw a new sample array each time you evaluate the number of rows.
Select an appropriate sample size.

In [18]:
# Enter code:

# Very advanced (Optional)

First, read all tasks in this section!


Implement the Hodgkin-Huxley model in numpy. Parameters and equations can be found here:
[https://neuronaldynamics.epfl.ch/online/Ch2.S2.html]()

In [27]:
# Enter code:

Implement the forward Euler method, e.g. described here [https://en.wikipedia.org/wiki/Euler_method]() as a function that can be used to simulate the HH neuron model described above.

In [28]:
# Enter code:

Simulate the response of the HH model to a step stimulus using your implementation of the FE method.

In [29]:
# Enter code: