In [80]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
from matplotlib import colors
import collections

In [174]:
## define state parameters

tree = 1
set_fire = 2
burnt = 3
# probability of growing a tree
grow_tree_prob = 0.1
fire_prob = 0.01

In [134]:
def init_forest(nx, ny, tree_density):
    """Create a forest as a grid of n x m size. 
    
    Input:
    n (int): width of forest grid.
    m (int): height of forest grid.
    tree_density (int): initial highest density of trees in forest.
    
    Output:
    n x m forest grid."""
    
    forest = np.zeros((nx, ny), dtype=int)
    forest[1:nx-1, 1:ny-1] = np.random.randint(0, 2, size=(nx-2,ny-2))
    # correct for density
    forest[1:nx-1, 1:ny-1] = np.random.random(size=(nx-2, ny-2)) < tree_density
    
    return forest

In [171]:
forest = init_forest(10, 10, 0.6)
print(forest)
# count the density of trees
np.count_nonzero(forest == 1) / 100

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 0 1 0]
 [0 1 1 1 1 0 1 0 1 0]
 [0 1 1 0 0 1 0 1 1 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 1 1 0 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0]
 [0 0 1 1 1 0 1 1 1 0]
 [0 1 0 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


0.41

In [173]:
forest.shape[0]

10

In [190]:
def set_fire(forest, x, y):
    """ Set fire at position x and y of the forest if there is any tree.

    Input:
    forest(array): array representing forest frid, created by init_forest() function.
    x(int), y(int): x and y location of tree which will be set on fire.
    
    
    post[forest]:
        If x, y is properly within the array, the tree at x, y is set.
        Otherwise, one tree in the center of the forest is set.
    """

    if x >= forest.shape[0] or y >= forest.shape[1]:
        raise TypeError("Don't exceed number of rows or columns")
    else:
        x = int(x)
        y = int(y)
        forest[x,y] = 2
        return forest

In [191]:
set_fire(forest, 2, 2)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 2, 1, 2, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])